"""
Opaque cursor codec (API_CONTRACT.md §4).

A cursor encodes the generation it was issued from, the normalized query
filters (``event_from``, ``event_to``, ``language``) and the normalized
``include`` set, plus the last ``(source_published_at, slug)`` of the page
that produced it. ``limit`` is deliberately **not** cursor-bound — the only
parameter with that exception — so a caller may change page size between
requests.

Cursors are generation- and query-bound: a generation switch between pages
fails with ``cursor_expired``; a changed normalized date range, language,
or ``include`` set fails with ``cursor_query_mismatch``. The API never
silently mixes pages from two generations, filters, or projections.

The token is integrity-protected: ``base64url(payload) "." base64url(HMAC-
SHA256(secret, payload))``. The secret is generated by the server at
startup (``generate_cursor_secret``) and never leaves the process — the
Bearer token is deliberately **not** used, because the caller holds it and
could then sign arbitrary cursors itself. Tampering therefore fails closed
with ``invalid_cursor`` instead of silently skipping or duplicating
records. A service restart invalidates outstanding cursors; clients
restart from page 1 (acceptable for short-lived pagination state — the
hourly pipeline cadence expires cursors on content changes anyway).
"""

import base64
import binascii
import datetime
import hashlib
import hmac
import json
import re
import secrets
from dataclasses import dataclass
from typing import Any, FrozenSet, Optional

from .export_pointer import parse_iso_timestamp

_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_CURSOR_VERSION = 1


def generate_cursor_secret() -> str:
    """A fresh server-only cursor-signing secret (256 bits). Generated once
    per service start; it is never persisted or exposed, so no caller —
    including the legitimate Bearer-token holder — can sign a cursor."""
    return secrets.token_urlsafe(32)


class CursorError(Exception):
    """Base class for cursor failures; ``code`` is the wire error code."""

    code = "invalid_cursor"


class CursorInvalidError(CursorError):
    """The token cannot be decoded or its payload is malformed."""

    code = "invalid_cursor"


class CursorExpiredError(CursorError):
    """The cursor's generation differs from the pointer's current
    generation (a new generation was published between pages)."""

    code = "cursor_expired"


class CursorQueryMismatchError(CursorError):
    """The cursor's normalized date range, language, or include set differs
    from the request's."""

    code = "cursor_query_mismatch"


@dataclass(frozen=True)
class DecodedCursor:
    generation: str
    event_from: datetime.date
    event_to: datetime.date
    language: str
    include: FrozenSet[str]
    last_source_published_at: str
    last_slug: str


def _signature(payload_b64: bytes, secret: str) -> str:
    digest = hmac.new(secret.encode("utf-8"), payload_b64, hashlib.sha256).digest()
    return base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")


def encode_cursor(
    *,
    secret: str,
    generation: str,
    event_from: datetime.date,
    event_to: datetime.date,
    language: str,
    include: FrozenSet[str],
    last_source_published_at: str,
    last_slug: str,
) -> str:
    payload = {
        "v": _CURSOR_VERSION,
        "generation": generation,
        "event_from": event_from.isoformat(),
        "event_to": event_to.isoformat(),
        "language": language,
        "include": sorted(include),
        "last_source_published_at": last_source_published_at,
        "last_slug": last_slug,
    }
    raw = json.dumps(payload, separators=(",", ":")).encode("utf-8")
    payload_b64 = base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")
    return f"{payload_b64}.{_signature(payload_b64.encode('ascii'), secret)}"


def _parse_date(value: Any) -> Optional[datetime.date]:
    if not isinstance(value, str) or _DATE_RE.match(value) is None:
        return None
    try:
        return datetime.date.fromisoformat(value)
    except ValueError:
        return None


def decode_cursor(token: str, *, secret: str) -> DecodedCursor:
    """Verify and decode a cursor token. The HMAC signature is checked
    before anything else — a re-encoded tampered payload fails closed with
    ``invalid_cursor``. Any shape violation is likewise an
    ``invalid_cursor`` 400 — tampering never degrades into a silent
    best-effort read."""
    if not isinstance(token, str) or not token:
        raise CursorInvalidError("cursor is empty or not a string")
    payload_b64, sep, sig = token.rpartition(".")
    if not sep or not payload_b64 or not sig:
        raise CursorInvalidError("cursor is not in the signed token form")
    # Both segments must be ASCII before the HMAC runs — a non-ASCII byte
    # string is by definition not a token this service issued, and an
    # unguarded encode here would leak UnicodeEncodeError as a 500.
    try:
        payload_b64_bytes = payload_b64.encode("ascii")
        provided_sig = sig.encode("ascii")
    except UnicodeEncodeError as e:
        raise CursorInvalidError("cursor segments are not ASCII base64url") from e
    expected_sig = _signature(payload_b64_bytes, secret).encode("ascii")
    if not hmac.compare_digest(provided_sig, expected_sig):
        raise CursorInvalidError("cursor signature mismatch")
    try:
        raw = base64.urlsafe_b64decode(payload_b64 + "=" * (-len(payload_b64) % 4))
        payload = json.loads(raw.decode("utf-8"))
    except (binascii.Error, UnicodeDecodeError, json.JSONDecodeError, ValueError) as e:
        raise CursorInvalidError(f"cursor is not decodable: {e}") from e
    if not isinstance(payload, dict) or payload.get("v") != _CURSOR_VERSION:
        raise CursorInvalidError("cursor payload has an unrecognized shape or version")

    generation = payload.get("generation")
    event_from = _parse_date(payload.get("event_from"))
    event_to = _parse_date(payload.get("event_to"))
    language = payload.get("language")
    include = payload.get("include")
    last_ts = payload.get("last_source_published_at")
    last_slug = payload.get("last_slug")

    if not isinstance(generation, str) or not generation:
        raise CursorInvalidError("cursor payload carries no valid generation")
    if event_from is None or event_to is None:
        raise CursorInvalidError("cursor payload carries invalid dates")
    if not isinstance(language, str) or not language:
        raise CursorInvalidError("cursor payload carries no valid language")
    if (
        not isinstance(include, list)
        or not all(isinstance(item, str) for item in include)
        or include != sorted(include)
    ):
        raise CursorInvalidError("cursor payload carries an invalid include set")
    if parse_iso_timestamp(last_ts) is None:
        raise CursorInvalidError("cursor payload carries an invalid position timestamp")
    if not isinstance(last_slug, str) or not last_slug:
        raise CursorInvalidError("cursor payload carries no valid position slug")

    return DecodedCursor(
        generation=generation,
        event_from=event_from,
        event_to=event_to,
        language=language,
        include=frozenset(include),
        last_source_published_at=last_ts,
        last_slug=last_slug,
    )


def check_cursor(
    cursor: DecodedCursor,
    *,
    generation: str,
    event_from: datetime.date,
    event_to: datetime.date,
    language: str,
    include: FrozenSet[str],
) -> None:
    """Bind the cursor to the current pointer generation and this request's
    normalized filters (API_CONTRACT.md §4). The client restarts from page
    1 on either failure."""
    if cursor.generation != generation:
        raise CursorExpiredError(
            f"cursor was issued from generation {cursor.generation}, but the "
            f"current generation is {generation}; restart from the first page"
        )
    if (
        cursor.event_from != event_from
        or cursor.event_to != event_to
        or cursor.language != language
        or cursor.include != include
    ):
        raise CursorQueryMismatchError(
            "cursor was issued for a different normalized date range, "
            "language, or include set; restart from the first page"
        )
